services:    
  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    restart: always

volumes:
  postgres-data:
  postgres-logs:
    