services:
  main:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '${PORT}:${PORT}'
    networks:
      - my-network
    depends_on:
      - postgres
    restart: always
    
  postgres:
    container_name: postgres
    build: 
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    restart: always
    networks:
      - my-network

networks:
  my-network:
    name: ${NETWORK}
    driver: ${DRIVER}
  

volumes:
  postgres-data:
  postgres-logs:
    