services:
  db:
    container_name: postgres
    image: postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    networks:
      - home-library-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}    

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - home-library-network
    ports:
      - ${PORT}:${PORT}
    container_name: home-library_app
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    restart: always

networks:
  home-library-network:
    driver: bridge
volumes:
  postgres_data:
  postgres_logs: